### ISSUE TITLE
Enable to create VPC and subnets in EC2 connector

### ISSUE THREAD

**Issue by micafer** [grycap/im#225]

**Comment by gmolto** [comment]
Why is this functionality required? 
IM should deploy virtual infrastructures on existing subnets of existing VPCs. 
What is the use case for dynamically creating a VPC and/or additional subnets?

It is very common that you have AWS credentials with privileges to run EC2 instances but maybe not to create VPC or subnets.

**Comment by micafer** [comment]
So in case that the user has not specified the VPC or subnet to use it can be interesting to list them and get the first VPC and Subnet available.
We must be careful with private nets without outbound conectivity.
