### ISSUE TITLE
Improve Error Message for InvalidParameterCombination

### ISSUE THREAD

**Issue by gmolto** [grycap/im#228]
When deploying an instance of AWS through the IM, depending on the combination of instance type and AMI it may fail throwing up this error:

InvalidParameterCombination</Code><Message>Non-Windows instances with a virtualization type of 'hvm' are currently not supported for this instance type.

In these circumstances, the error message does not show the AMI, instance type, VPC id and subnet id. Showing this information in the error message may better help isolate the root cause of error.

**Comment by micafer** [comment]
Merged and tested.
