### ISSUE TITLE
Authorization file format does not allow passwords that contain ";"

### ISSUE THREAD

**Issue by jartitodebuscarusuario** [grycap/im#509]
Function read_auth_data in IM/auth.py uses split by ";" to parse auth data in authorization files, preventing the use of semicolon in passwords. As a suggest, maybe the only change needed is to split by "; " (semicolon + space) instead of splitting by semicolon.

Regards,

Andrés

**Comment by micafer** [comment]
Hi @jartitodebuscarusuario,

We have fixed this bug using quotes:
```
password = 'some;password'
```
See PR: #510

Regards.
