### ISSUE TITLE
PyCrypto library missing from the grycap/im container image

### ISSUE THREAD

**Issue by alahiff** [grycap/im#569]
When using the grycap/im:1.6.7 Docker image I get this error when trying to deploy something on Google:
```
GoogleAuthError: 'PyCrypto library required for Service Account Authentication.'
```
This problem does not occur with indigodatacloud/im:1.6.7.

**Comment by micafer** [comment]
I have uploaded a new docker image (1.6.7-1) that install this library.
Could you please test iT?

**Comment by alahiff** [comment]
Thanks, the new image resolves this problem.
