### ISSUE TITLE
SSL errors on OCCI sites only when IM REST API is used

### ISSUE THREAD

**Issue by alahiff** [grycap/im#636]
Whenever I try to use the REST API to deploy infrastructure, e.g.
```
$ curl -X POST --header "Content-Type:text/plain" --header "Authorization:id = occi6; type = OCCI; proxy = file(/tmp/x509up_u1001); host = http://cloud.recas.ba.infn.it:8787/occi;\n id = im; type = InfrastructureManager; username = user; password = pass" --data-binary @/tmp/job-1695-1528010549.radl http://localhost:8800/infrastructures
```
I get an error like this for EGI FedCloud OpenStack sites (e.g. RECAS-BARI or IN2P3-IRES):
```
Error obtaining Keystone v2 Token: HTTPSConnectionPool(host='cloud.recas.ba.infn.it', port=5000): Max retries exceeded with url: /v2.0/tokens (Caused by SSLError(SSLError(336445449, u'[SSL] PEM lib (_ssl.c:2584)'),))
```
If I use python-requests instead of curl the same thing happens.

But im_client.py, using the IM XMLRPC URL, works fine and there are no problems! Note that in both cases I'm using the same proxy, the same site and the same RADL file.

**Comment by micafer** [comment]
Hi @alahiff,

The header that you are sending using the curl command is not correct. 
The call 'file(/tmp/x509up_u1001)' is only allowed to be used with the im_client that reads the file and sends the contents of the file to the IM service.
If you use curl command you have to send the content of the proxy replacing the "newline char" of the file with "\\n".
But you can now use the IM client to contact the REST API of the IM to make easier these calls to the IM.

**Comment by alahiff** [comment]
Hi @micafer,

Thanks! Sorry, I somehow missed that obvious mistake. Closing the ticket.
