### ISSUE TITLE
IM 1.7.3 and OCCI server 2.0.4 authentication error

### ISSUE THREAD

**Issue by victorsndvg** [grycap/im#656]
Hi IM team,

one the of the fedcloud VO members has planned an  OCCI server upgrade from version 2.0.0 to  2.0.4.

Version 2.0.0 is currently working in production in:
- https://fedcloud-services.egi.cesga.es:11443

A canary tested of  2.0.4 version is deployed at:
- https://fedcloud-cmdone.egi.cesga.es:11443/

We have checked that 2.0.4 version works with occi-cli versión 4.3.10 but not with 4.3.9. With 4.3.9 we get the following error:
```
F, [2018-09-06T08:42:22.126569 #53] FATAL -- : [rOCCI-cli] An error 
occurred! Message: Unable to get Keystone API version from the response, 
fallback failed
```

I'm trying to deploy some VMs with the production (occi server 2.0.0) version and everything runs smoothly, but with the testbed (occi server 2.0.4) version it fails with the following error:

```
	Error Creating Inf.: Error launching the VMs of type node to cloud ID test of type OCCI. Attempt 1: Unauthorized
Not authorized to access requested content
```
Both errors are related with authentication, but not sure if are related between them.

The endpoint and image url are as follows:
- endpoint: "https://fedcloud-cmdone.egi.cesga.es:11443/"
- disk.0.image.url: 'https://fedcloud-cmdone.egi.cesga.es:11443/51' 

The radl looks like:  
```
network  net  ( 
    outbound = 'yes'
)       
system node (
    instance_name = 'mso4sc' and
    cpu.arch = 'x86_64' and
    cpu.count = 1 and
    memory.size = 1024M and
    image_type = 'qcow2' and
    virtual_system_type = 'kvm' and
    net_interface.0.connection = 'net' and
    disk.0.image.url = 'https://fedcloud-cmdone.egi.cesga.es:11443/51' and
    disk.0.os.credentials.username = 'XXX' and
    disk.0.os.credentials.password = 'XXX' and
    disk.0.os.credentials.public_key = 'XXX'
)
deploy node 1
```
Do you know if IM 1.7.3 works with occi server 2.0.4?
If yes, am I doing something wrong? 
How can I fix it?

Thanks in advance!

**Comment by micafer** [comment]
We have tested it and it is failing.
It seems that the keystone implementation of the OCCI server 2.0.4 is not compatible with the OpenStack one.
We are investigating.

**Comment by victorsndvg** [comment]
Thanks @micafer ,

let me know when something is ready for testing and also if we can help.

**Comment by micafer** [comment]
Hi @victorsndvg,
You can download the new version of the OCCI connector or apply the changes made in this commit: https://github.com/grycap/im/commit/1c737d81d83d3734a72ca9268daca88597503b17 in your own version.
I have tested and it seems to work fine.
Could you please test it?

**Comment by victorsndvg** [comment]
Yes, sure!

Is there a way to get this brand new dev version in a docker container? 
If I should build the container, which is the righ dir (docker, docker-dev, docker-python3)?

Thanks for your quick response!

**Comment by micafer** [comment]
Hi @victorsndvg ,

You can try the version 1.7.4-dev pushed in dockerhub.

**Comment by victorsndvg** [comment]
HI @micafer ,

it seems that latest commit 59f6c79 is not included in the `1.7.4-dev` dockerhub IM image.

I was able to test with this docker image and the error is still there:
```
2018-09-07 11:30:29,861 - CloudConnector - WARNING - Inf ID: 5923146e-b291-11e8-8fb4-0242ac120002: Old Keystone token invalid.
2018-09-07 11:30:29,862 - CloudConnector - INFO - Inf ID: 5923146e-b291-11e8-8fb4-0242ac120002: Getting Keystone v3 token
2018-09-07 11:30:31,291 - CloudConnector - INFO - Inf ID: 5923146e-b291-11e8-8fb4-0242ac120002: Using project: fedcloud.egi.eu
2018-09-07 11:30:32,578 - InfrastructureManager - ERROR - Error launching some of the VMs: Attempt 1: Conflict
Invalid content: Submitted entity is not compliant with server restrictions
Attempt 2: Conflict
Invalid content: Submitted entity is not compliant with server restrictions
Attempt 3: Conflict
Invalid content: Submitted entity is not compliant with server restrictions
```

any other thing I can do?

**Comment by micafer** [comment]
The fix is included. As you can see the error is different:

Try this RADL
```
network  net  ( 
    outbound = 'yes'
)       
system node (
    instance_type = 'small' and
    net_interface.0.connection = 'net' and
    disk.0.image.url = 'https://fedcloud-cmdone.egi.cesga.es:11443/51'
)
deploy node 1
```
And then add the modifications that you need.

**Comment by victorsndvg** [comment]
Ok, thanks @micafer , 

this RADL seems to work. 

Great, good job!
