### ISSUE TITLE
is IM aware of cloud_init finalization?

### ISSUE THREAD

**Issue by victorsndvg** [grycap/im#660]
Hi IM team,

I'm using IM REST API to deploy a VM. The RADL install some software with cloud_init during contextualization.

The RADL looks like this:
```
configure sleep (
@begin
final_message: "The system is finally up, after $UPTIME seconds 1"
runcmd:
    - sleep 10m
)
network  net  ( 
    outbound = 'yes'
)       
system node (
    instance_type = 'small' and
    net_interface.0.connection = 'net' and
    disk.0.image.url = 'https://fedcloud-cmdone.egi.cesga.es:11443/51'
)
deploy node 1

contextualize (
   system node configure sleep with cloud_init
)
```
Once the VM is deployed, it jumps quite fast to `configured` state (I'm using IM to know the status of the VM). The issue here is that I'm able to connect to the VM, but cloud_init contextualization is still running.

Is there a way to know when cloud_init contextualization finish?

am I doing something wrong or misunderstanding something?

Thanks in advance!

**Comment by micafer** [comment]
In case of using cloud_init. The IM does not control the finalization of the contextualization.

**Comment by victorsndvg** [comment]
Thanks @micafer ,

lets try to use Ansible instead.

feel free to close the issue.
