### ISSUE TITLE
Problems using tokens with OpenStack (caching on server?)

### ISSUE THREAD

**Issue by alahiff** [grycap/im#808]
I'm using an auth line like this in order to access an EGI FedCloud site using token-based authentication:
```
id = <site>; type = OpenStack; host = <endpoint>; username = egi.eu; tenant = openid; password = <token>; auth_version = 3.x_oidc_access_token; base_url = <base_url>; network_url = <network_url>; image_url = <image_url>
```
(see https://github.com/grycap/im/issues/772).

The tokens provided by EGI Check-in have a life time of 3600s. If I deploy infrastructure, then try to do a "getstate" or "destroy" with a new token after the original token has expired, IM gives me an "Invalid credentials with the provider" error.

If I then restart the IM server (by restarting the Docker container), suddently everything starts working and I can do a "getstate" or "destroy" successfully. This is using exactly the same token which previously resulted in an "Invalid credentials with the provider" .

I know IM does not store credentials and so the client always needs to provide them, but it does appear that tokens are being cached in some way and a restart is needed in order to clear them.

**Comment by alahiff** [comment]
It does seem that until the IM server is restarted, the token that was used to originally create the infrastructure is always used, irrespective of what is provided by the IM client. I noticed that if I create a VM using an auth file with a valid token, then destroy the VM using a different auth file specifying a token which expired long ago, the VM is successfully destroyed, when of course it should fail.

**Comment by micafer** [comment]
Hi @alahiff,
IM caches some auth information in memory. 
But it checks if the new auth data provided by the user is different and deletes the cache and uses the new auth data provided.
I have made some tests with the OpenStack connector and I cannot get this problem.
What IM version are you using?

**Comment by alahiff** [comment]
Thanks for checking. I was using 1.8.1. Right now I can't actually reproduce the problem, but I'm doing more tests to see if I can. Last week I had experienced this issue frequently, so I'm not sure what's changed.

**Comment by micafer** [comment]
Finally I think I get the origin of this error.
It only happens in case that you are using two or more OpenStack auth data. In this case the IM fails checking if the new auth data provided by the user is different and deletes the cache and uses the new auth data provided.
