### ISSUE TITLE
updated links for indigo-dc repositories

### ISSUE THREAD

**Issue by caifti** [grycap/im#834]
The INDIGO-DC repositories have changed from http to https.
The file conf-ansible.yml needs to be updated as follows:
line 55:  - apt_key: url=https://repo.indigo-datacloud.eu/repository/RPM-GPG-KEY-indigodc state=present
line 59: apt: deb=https://repo.indigo-datacloud.eu/repository/indigo/1/ubuntu/dists/trusty-updates/main/binary-amd64/indigodc-release_1.0.0-2_amd64.deb
line 83: rpm_key: state=present key=https://repo.indigo-datacloud.eu/repository/RPM-GPG-KEY-indigodc
line 87: yum: state=present name=https://repo.indigo-datacloud.eu/repository/indigo/2/centos7/x86_64/base/indigodc-release-2.0.0-1.el7.centos.noarch.rpm

**Comment by caifti** [comment]
forgot to mention (I thought I did it yesterday ... but it seems got lost) - there is also the ansible-install that needs the same treatment:
            wget -q -O - https://repo.indigo-datacloud.eu/repository/RPM-GPG-KEY-indigodc | sudo apt-key add -
                    wget https://repo.indigo-datacloud.eu/repository/indigo/1/ubuntu/dists/trusty-updates/main/binary-amd64/indigodc-release_1.0.0-2_amd64.deb
                    wget https://repo.indigo-datacloud.eu/repository/indigo/2/ubuntu/dists/xenial/main/binary-amd64/indigodc-release_2.0.0-1_amd64.deb
            yum install -y https://repo.indigo-datacloud.eu/repository/indigo/2/centos7/x86_64/base/indigodc-release-2.0.0-1.el7.centos.noarch.rpm

at least the ansible-install.sh that I find in the containerv deploying the image tagged 1.8.2. It seems it is different from the onw I'm able to read in github.

**Comment by micafer** [comment]
This issue is related with the indigo-dc version.
I close this issue and move it to the indigo-dc repo.
