### ISSUE TITLE
Optional tenant name for OpenStack using VOMS authentication

### ISSUE THREAD

**Issue by nakos** [grycap/im#871]
During the development  in EGI VMOPs dashboard for supporting OpenStack endpoints we noticed that the IM authentication scheme requires the tenant name to be provided. However, in the case of VOMS authentication, that we currently work with, this attribute can be omitted and the libcloud will retrieve the tenant name by creating an unscoped token in [OpenStackIdentity_2_0_Connection_VOMS](https://github.com/apache/libcloud/blob/trunk/libcloud/common/openstack_identity.py#L1628). 

Can this attribute become optional in IM in case of VOMS authentication?

**Comment by micafer** [comment]
Hi @nakos,
You are rigth. I will make this field optional.
