### ISSUE TITLE
Support for adding block storage and networks to running VMs with OpenStack

### ISSUE THREAD

**Issue by nakos** [grycap/im#872]
In the EGI VMOps dashboard we are able to add block storages and add/remove networks to running VMs, when using the IM OCCI connector, by sending a new RADL document to the appropriate REST endpoint of IM. Now that we are trying to support OpenStack endpoints, we noticed that such an implementation seems to be missing, in the case of the OpenStack connector. 

Would it be possible to add such a functionality to the OpenStack connector?

**Comment by micafer** [comment]
Hi @nakos,
Adding storages can be added.
When you say adding/removing networks, in fact in the OCCI case it only applies to add/remove public IPs. In this case it can also added to the OpenStack conn.
I will check.

**Comment by nakos** [comment]
Yes, you are right, we are adding or removing public IPs and not networks. Thanks.
