### ISSUE TITLE
Enable to get info from VM images from AppDB/AppDBIS or CMDB

### ISSUE THREAD

**Issue by micafer** [grycap/im#978]

**Comment by micafer** [comment]
One problem with this solution is that there are many EGI Cloud Compute site that does not publish their images at AppDB, so this solution will not work with all the sites.

**Comment by micafer** [comment]
hi @sebastian-luna-valero,

In case of AppDB we have it partially developed this functionality. 
I have some delay releasing it ....

But in case of using cloud site images, it is not possible as there is no metadata about the images and it is not standard so the only way is to search is using the image name. Furthermore it will require a lot of time, as it will require to query a lot of sites ...
I have discarded this idea,

**Comment by sebastian-luna-valero** [comment]
I understand. Thanks, @micafer
